"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Shape_1 = require("./Shape");
var Circle_1 = require("./Circle");
var Rectangle_1 = require("./Rectangle");
var shape = new Shape_1.Shape(5, 10);
console.log(shape.getInfo());
var circle = new Circle_1.Circle(15, 20, 5);
console.log(circle.getInfo());
var rectangle = new Rectangle_1.Rectangle(400, 122, 121, 22);
console.log(rectangle.getInfo());
