var first_name = "Akshay";
var last_name = "A";
var Age = 23;
var ismale = true;
var doescode = true;
console.log("First Name :" + first_name);
console.log("Last Name :" + last_name);
console.log("Age :" + Age);
console.log("Male :" + ismale);
console.log("Hi welcome " + first_name + " " + last_name);
